### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by Hsiao-Feng** [kraity/Dynamics#11]
发布之后的时区貌似是 UTC 时间，而非 Typecho 系统设置的时区时间。

有没有什么办法可以解决这个问题？

**Comment by MliKiowa** [comment]
Typecho内置了时间操作但是插件没有用到
https://github.com/typecho/typecho/blob/master/var/Typecho/Date.php
而是自己实现了时间处理https://github.com/krait-team/Dynamics-typecho/blob/master/Dynamic.php#L333

**Comment by Hsiao-Feng** [comment]
> Typecho内置了时间操作但是插件没有用到 https://github.com/typecho/typecho/blob/master/var/Typecho/Date.php 而是自己实现了时间处理https://github.com/krait-team/Dynamics-typecho/blob/master/Dynamic.php#L333

好的，谢谢你！
